#!/bin/bash
image_weights_csv=/Users/$USER/imagecloud/imagecloud-import.csv
image_cloud_png=/Users/$USER/imagecloud/li/li_imagecloud.png
layout_dir=/Users/$USER/imagecloud/li
image_type=png

linkedin_background_size="2814,705"
reasonable_smallest_size="50,50"
if [ ! -d "$layout_dir" ]; then
    mkdir -p $layout_dir
fi

generate_imagecloud \
    -i $image_weights_csv \
    -output_image_filepath $image_cloud_png \
    -output_layout_dirpath $layout_dir \
    -output_image_format $image_type \
    -cloud_size $linkedin_background_size \
    -min_image_size $reasonable_smallest_size \
    -maintain_aspect_ratio \
    -show