#!/bin/bash
input_csv=/Users/$USER/imagecloud/li/imagecloud_layout.csv
output_directory=/Users/$USER/imagecloud/li
image_type=png

layout_imagecloud \
    -i $input_csv \
    -output_directory $output_directory \
    -output_image_format $image_type \
    -maximize_empty_space \
    -show_imagecloud \
    -show_imagecloud_reservation_chart